services:
  - type: web
    name: currency-atm
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ADMIN_TOKEN
        sync: false
